import { buildFifeLifeNextReward, type CustomerLoyaltyOverview } from "./customer-loyalty-overview";

/** Données d’aperçu pour le mode démo client (jamais utilisées en production). */
export const DEMO_LOYALTY_OVERVIEW: CustomerLoyaltyOverview = {
  nextReward: null,
  cardRewards: [
    {
      cardKey: "global",
      cardType: "global",
      membershipId: null,
      merchantId: null,
      slug: "fife-life",
      nextReward: buildFifeLifeNextReward(180),
      availableReward: null,
      progress: { current: 180, target: 250, percent: 53, unit: "points" },
    },
    {
      cardKey: "preview-cafe",
      cardType: "merchant",
      membershipId: "preview-cafe",
      merchantId: "cafe-demo",
      slug: "cafe-demo",
      nextReward: {
        rewardName: "Boisson offerte",
        merchantId: "cafe-demo",
        merchantName: "Café Demo",
        merchantSlug: "cafe-demo",
        merchantLogoUrl: null,
        statusLabel: "Encore 3 passages chez Café Demo",
        progressCurrent: 7,
        progressTarget: 10,
        progressPercent: 70,
        unit: "passages",
        available: false,
        mode: "VISITS",
      },
      availableReward: null,
      progress: { current: 7, target: 10, percent: 70, unit: "passages" },
    },
    {
      cardKey: "preview-hotel",
      cardType: "merchant",
      membershipId: "preview-hotel",
      merchantId: "m-hotel",
      slug: "prism-hotel",
      nextReward: {
        rewardName: "Nuit offerte",
        merchantId: "m-hotel",
        merchantName: "Prism Hôtel",
        merchantSlug: "prism-hotel",
        merchantLogoUrl: null,
        statusLabel: "Encore 3 passages chez Prism Hôtel",
        progressCurrent: 7,
        progressTarget: 10,
        progressPercent: 70,
        unit: "passages",
        available: false,
        mode: "VISITS",
      },
      availableReward: null,
      progress: { current: 7, target: 10, percent: 70, unit: "passages" },
    },
    {
      cardKey: "preview-nova",
      cardType: "merchant",
      membershipId: "preview-nova",
      merchantId: "m-nova",
      slug: "brasserie-nova",
      nextReward: {
        rewardName: "Dessert offert",
        merchantId: "m-nova",
        merchantName: "Brasserie Nova",
        merchantSlug: "brasserie-nova",
        merchantLogoUrl: null,
        statusLabel: "Encore 4 passages chez Brasserie Nova",
        progressCurrent: 4,
        progressTarget: 8,
        progressPercent: 50,
        unit: "passages",
        available: false,
        mode: "VISITS",
      },
      availableReward: null,
      progress: { current: 4, target: 8, percent: 50, unit: "passages" },
    },
    {
      cardKey: "preview-cinema",
      cardType: "merchant",
      membershipId: "preview-cinema",
      merchantId: "m-cinema",
      slug: "cinema-lumiere",
      nextReward: {
        rewardName: "Séance offerte",
        merchantId: "m-cinema",
        merchantName: "Cinéma Lumière",
        merchantSlug: "cinema-lumiere",
        merchantLogoUrl: null,
        statusLabel: "Encore 1 passage chez Cinéma Lumière",
        progressCurrent: 9,
        progressTarget: 10,
        progressPercent: 90,
        unit: "passages",
        available: false,
        mode: "VISITS",
      },
      availableReward: null,
      progress: { current: 9, target: 10, percent: 90, unit: "passages" },
    },
  ],
  recentActivity: [
    {
      id: "demo-a1",
      merchantId: "m-nova",
      merchantName: "Brasserie Nova",
      merchantSlug: "brasserie-nova",
      merchantLogoUrl: null,
      createdAt: new Date(Date.now() - 3600_000).toISOString(),
      type: "EARN_VISIT",
      title: "Achat validé",
      detail: "Achat de 48,00 €",
      lineLabel: "Brasserie Nova · Achat de 48,00 €",
      deltaLabel: "+480 points",
      formattedDate: "Aujourd'hui à 14:32",
      purchaseAmountCents: 4800,
      status: "completed",
    },
    {
      id: "demo-a2",
      merchantId: "m-cinema",
      merchantName: "Cinéma Lumière",
      merchantSlug: "cinema-lumiere",
      merchantLogoUrl: null,
      createdAt: new Date(Date.now() - 86400_000).toISOString(),
      type: "EARN_VISIT",
      title: "Achat validé",
      detail: "2 places",
      lineLabel: "Cinéma Lumière · 2 places",
      deltaLabel: "+260 points",
      formattedDate: "Hier à 18:15",
      purchaseAmountCents: null,
      status: "completed",
    },
    {
      id: "demo-a3",
      merchantId: "m-hotel",
      merchantName: "Prism Hôtel",
      merchantSlug: "prism-hotel",
      merchantLogoUrl: null,
      createdAt: new Date(Date.now() - 172800_000).toISOString(),
      type: "EARN_VISIT",
      title: "Passage validé",
      detail: "Check-in",
      lineLabel: "Prism Hôtel · Check-in",
      deltaLabel: "+1 passage",
      formattedDate: "9 septembre à 09:40",
      purchaseAmountCents: null,
      status: "completed",
    },
  ],
  activityTotal: 3,
};
