import type { CustomerLoyaltyOverview } from "./customer-loyalty-overview";

/** Données d’aperçu pour le mode démo client (jamais utilisées en production). */
export const DEMO_LOYALTY_OVERVIEW: CustomerLoyaltyOverview = {
  nextReward: {
    rewardName: "Nuit offerte",
    merchantId: "m-hotel",
    merchantName: "Prism Hôtel",
    merchantSlug: "prism-hotel",
    merchantLogoUrl: null,
    statusLabel: "Encore 1 240 points",
    progressCurrent: 760,
    progressTarget: 2000,
    progressPercent: 38,
    unit: "points",
    available: false,
    mode: "POINTS_BY_AMOUNT",
  },
  recentActivity: [
    {
      id: "demo-a1",
      merchantId: "m-nova",
      merchantName: "Brasserie Nova",
      merchantSlug: "brasserie-nova",
      merchantLogoUrl: null,
      createdAt: new Date(Date.now() - 3600_000).toISOString(),
      type: "EARN_VISIT",
      title: "Achat validé",
      detail: "Achat de 48,00 €",
      lineLabel: "Brasserie Nova · Achat de 48,00 €",
      deltaLabel: "+480 points",
      formattedDate: "Aujourd'hui à 14:32",
      purchaseAmountCents: 4800,
      status: "completed",
    },
    {
      id: "demo-a2",
      merchantId: "m-cinema",
      merchantName: "Cinéma Lumière",
      merchantSlug: "cinema-lumiere",
      merchantLogoUrl: null,
      createdAt: new Date(Date.now() - 86400_000).toISOString(),
      type: "EARN_VISIT",
      title: "Achat validé",
      detail: "2 places",
      lineLabel: "Cinéma Lumière · 2 places",
      deltaLabel: "+260 points",
      formattedDate: "Hier à 18:15",
      purchaseAmountCents: null,
      status: "completed",
    },
    {
      id: "demo-a3",
      merchantId: "m-hotel",
      merchantName: "Prism Hôtel",
      merchantSlug: "prism-hotel",
      merchantLogoUrl: null,
      createdAt: new Date(Date.now() - 172800_000).toISOString(),
      type: "EARN_VISIT",
      title: "Passage validé",
      detail: "Check-in",
      lineLabel: "Prism Hôtel · Check-in",
      deltaLabel: "+1 passage",
      formattedDate: "9 septembre à 09:40",
      purchaseAmountCents: null,
      status: "completed",
    },
  ],
  activityTotal: 3,
};
