import type { MerchantCardData } from "./types";
import type { ProfilePayload, PreferencesPayload } from "@/lib/customer-profile";
import type { BenefitEntry, HistoryEntry } from "@/lib/customer-history";

export const PREVIEW_PROFILE: ProfilePayload = {
  id: "preview-user",
  firstName: "Marie",
  lastName: "Thérèse",
  displayName: null,
  email: "marie@example.com",
  pendingEmail: null,
  avatarUrl: null,
  phone: "6 12 34 56 78",
  phoneCountryCode: "+33",
  phoneVerified: false,
  addressLine1: "12 Rue des Lilas",
  addressLine2: null,
  postalCode: "75011",
  city: "Paris",
  country: "FR",
  authMethod: "password",
  hasPassword: true,
};

export const PREVIEW_PREFERENCES: PreferencesPayload = {
  notifyPointsMovements: true,
  notifyNewBenefit: true,
  notifyBenefitExpiring: true,
  notifyNewCard: true,
  notifyMerchantOffers: false,
  notifyFifeLifeNews: false,
  notifySecurity: true,
  notifyChannelPush: true,
  notifyChannelEmail: true,
  notifyChannelSms: false,
  consentPersonalizedOffers: false,
  consentMarketing: false,
  consentAnalytics: false,
  language: "fr",
};

export const PREVIEW_PROFILE_HISTORY: HistoryEntry[] = [
  {
    id: "h-pizza",
    merchantId: "m-pizza",
    merchantName: "Pizza Time",
    merchantLogoUrl: null,
    createdAt: new Date(Date.now() - 3600_000).toISOString(),
    operationType: "Points gagnés",
    operationLabel: "+35 points",
    pointsDelta: 35,
    passagesDelta: null,
    amountCents: null,
    reason: "Achat",
    status: "completed",
    category: "earned",
    tone: "gain",
  },
  {
    id: "h-hotel",
    merchantId: "m-hotel",
    merchantName: "Prism Hôtel",
    merchantLogoUrl: null,
    createdAt: new Date(Date.now() - 86400_000).toISOString(),
    operationType: "Passage ajouté",
    operationLabel: "+1 passage",
    pointsDelta: null,
    passagesDelta: 1,
    amountCents: null,
    reason: "Check-in",
    status: "completed",
    category: "earned",
    tone: "gain",
  },
  {
    id: "h-benny",
    merchantId: "m-benny",
    merchantName: "Benny's Pizza",
    merchantLogoUrl: null,
    createdAt: new Date(Date.now() - 172800_000).toISOString(),
    operationType: "Points utilisés",
    operationLabel: "−100 points",
    pointsDelta: -100,
    passagesDelta: null,
    amountCents: null,
    reason: "Récompense",
    status: "completed",
    category: "used",
    tone: "use",
  },
  {
    id: "h-nova",
    merchantId: "m-nova",
    merchantName: "Café Nova",
    merchantLogoUrl: null,
    createdAt: new Date(Date.now() - 259200_000).toISOString(),
    operationType: "Points expirés",
    operationLabel: "50 points expirés",
    pointsDelta: -50,
    passagesDelta: null,
    amountCents: null,
    reason: "Expiration annuelle",
    status: "completed",
    category: "expired",
    tone: "expire",
  },
  {
    id: "h-solstice",
    merchantId: "m-solstice",
    merchantName: "Maison Solstice",
    merchantLogoUrl: null,
    createdAt: new Date(Date.now() - 345600_000).toISOString(),
    operationType: "Correction",
    operationLabel: "Correction +20 points",
    pointsDelta: 20,
    passagesDelta: null,
    amountCents: null,
    reason: "Erreur caisse",
    status: "completed",
    category: "correction",
    tone: "correction",
  },
];

export const PREVIEW_BENEFITS: BenefitEntry[] = [
  {
    id: "b-hotel",
    merchantId: "m-hotel",
    merchantName: "Prism Hôtel",
    merchantLogoUrl: null,
    benefitName: "Une nuit offerte",
    usedAt: new Date("2026-08-12").toISOString(),
    costLabel: "10 passages",
    status: "used",
    expiresBeforeUse: null,
  },
  {
    id: "b-pizza",
    merchantId: "m-pizza",
    merchantName: "Pizza Time",
    merchantLogoUrl: null,
    benefitName: "Une pizza offerte",
    usedAt: new Date("2026-08-28").toISOString(),
    costLabel: "500 points",
    status: "used",
    expiresBeforeUse: null,
  },
];

export const PREVIEW_CARDS: MerchantCardData[] = [
  {
    id: "preview-hotel",
    merchantId: "m-hotel",
    slug: "prism-hotel",
    name: "Prism Hôtel",
    logoUrl: null,
    primaryColor: "#7085ff",
    points: 7,
    visitsRequired: 10,
    rewardLabel: "Nuit offerte",
  },
  {
    id: "preview-nova",
    merchantId: "m-nova",
    slug: "brasserie-nova",
    name: "Brasserie Nova",
    logoUrl: null,
    primaryColor: "#e774ff",
    points: 4,
    visitsRequired: 8,
    rewardLabel: "Dessert offert",
  },
  {
    id: "preview-cinema",
    merchantId: "m-cinema",
    slug: "cinema-lumiere",
    name: "Cinéma Lumière",
    logoUrl: null,
    primaryColor: "#8557ff",
    points: 9,
    visitsRequired: 10,
    rewardLabel: "Séance offerte",
  },
];

export const PREVIEW_HISTORY: import("./types").CardHistoryItem[] = [
  {
    id: "h1",
    type: "EARN_VISIT",
    pointsDelta: 480,
    reason: "Brasserie Nova",
    createdAt: new Date(Date.now() - 3600_000).toISOString(),
  },
  {
    id: "h2",
    type: "EARN_VISIT",
    pointsDelta: 260,
    reason: "Cinéma Lumière",
    createdAt: new Date(Date.now() - 86400_000).toISOString(),
  },
  {
    id: "h3",
    type: "REDEEM_REWARD",
    pointsDelta: -1200,
    reason: "Prism Hôtel · Check-in",
    createdAt: new Date(Date.now() - 172800_000).toISOString(),
  },
];

export const PREVIEW_QR =
  "data:image/svg+xml;utf8," +
  encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect fill="#fff" width="32" height="32"/><rect fill="#0F172A" x="2" y="2" width="8" height="8"/><rect fill="#0F172A" x="22" y="2" width="8" height="8"/><rect fill="#0F172A" x="2" y="22" width="8" height="8"/><rect fill="#0F172A" x="13" y="13" width="6" height="6"/><rect fill="#0F172A" x="12" y="4" width="2" height="2"/><rect fill="#0F172A" x="16" y="4" width="2" height="2"/><rect fill="#0F172A" x="18" y="8" width="2" height="2"/><rect fill="#0F172A" x="4" y="12" width="2" height="2"/><rect fill="#0F172A" x="8" y="16" width="2" height="2"/><rect fill="#0F172A" x="20" y="18" width="2" height="2"/><rect fill="#0F172A" x="24" y="14" width="2" height="2"/><rect fill="#0F172A" x="14" y="22" width="2" height="2"/><rect fill="#0F172A" x="18" y="26" width="2" height="2"/></svg>`,
  );
